# Site settings
title: DA Lang
SEOTitle: DA Lang | åšå®¢
header-img: img/post-home.jpg
email: dalang1hao@gmail.com
description: "å’¸é±¼ä¸€æ¡ï¼"
keyword: "DA Lang, dalang, å¤§éƒ, å¤§éƒçš„åšå®¢, dalangblog ,æ–è®¯, N1, T1, åšå®¢, ä¸ªäººç½‘ç«™, äº’è”ç½‘, Web, ios, Apple, iPhone, OpenWrt, OpenClash"
url: "https://dalangblog.ga"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: false
# weibo_username:     dalangblog
zhihu_username:     lang-er-lang-er-lang-10
github_username:    dalangblog
# twitter_username:   dalangblog
# facebook_username:  dalangblog
# linkedin_username:  firstname-lastname-idxxxx



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN  



# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1



# Disqus settings
# disqus_username: dalangblog

# Gitalk
gitalk:
  enable: true    #æ˜¯å¦å¼€å¯Gitalkè¯„è®º
  clientID: 351fa4a0808c02127803                            #ç”Ÿæˆçš„clientID
  clientSecret: 39ea81c069a1a2910a3fc560898af29369595f3d    #ç”Ÿæˆçš„clientSecret
  repo: dalangblog.github.io    #ä»“åº“åç§°
  owner: dalangblog    #githubç”¨æˆ·å
  admin: dalangblog
  distractionFreeMode: true #æ˜¯å¦å¯ç”¨ç±»ä¼¼FBçš„é˜´å½±é®ç½©

# Netease settings
netease_comment: false



# Analytics settings
# Baidu Analytics 
# ba_track_id: [your track id]

# Google Analytics
ga_track_id: 'UA-195407239-1'            # Format: UA-xxxxxx-xx
ga_domain: dalangblog.ga



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Knowledge is power!"
sidebar-avatar: /img/avatar-DA-Lang.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false



# Friends
friends: [
    {
        title: "Apple(ä¸­å›½å¤§é™†)",
        href: "https://www.apple.com.cn/"
    },{
        title: "ç®¡ç†æ‚¨çš„ Apple ID",
        href: "https://appleid.apple.com/cn/"
    },{
        title: "ğŸ¤£ Emojiè¡¨æƒ…å¤§å…¨",
        href: "https://emojixd.com/"
    }  
]
